[package]
name = "rupring"
version = "0.1.0"
edition = "2021"
description = "rupring"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rupring_macro={ version="0.1.0", path="../rupring_macro" }
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1.0"
hyper-util = { version = "0.1", features = ["full"] }
bytes = "1.5.0"
