[package]
name = "rupring_macro"
version = "0.4.0"
edition = "2021"
description = "rupring macro"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
proc-macro=true