//! Scalar API Reference viewer for OpenAPI documents.
//!
//! This module owns only the Scalar viewer route. It consumes the OpenAPI
//! document generated by [`crate::openapi`].

pub mod controller;
pub mod html;
pub mod module;
pub mod routes;
