[package]
name = "rupring_example"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.1"
rupring={ version = "0.11.0" }
# rupring={ path="../rupring" }
serde = { version="1.0.193", features=["derive"] }
