//! Swagger UI viewer for OpenAPI documents.
//!
//! This module owns only the Swagger UI routes and static assets. It consumes
//! the OpenAPI document generated by [`crate::openapi`].

pub mod controller;
pub mod html;
pub mod module;
pub mod routes;
pub mod swagger_ui_bundle;
pub mod swagger_ui_css;
