name: Clippy

on:
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup component add clippy --toolchain 1.87.0

      - name: Run Clippy
        run: rustup run 1.87.0 cargo clippy
